export const pedidosData = [
  {
    entradaDocumento: 11,
    fechaDocumento: "2025-11-25T00:00:00",
    fechaCreacion: "2025-11-25T00:00:00",
    fechaActualizacion: "2025-11-25T00:00:00",
    codigoCliente: "C0000011",
    nombreCliente: "Ana Rodríguez",
    direccionEnvio: "Calle Gran Vía 78, Madrid",
    importeTotal: 28.50,
    importeIVA: 2.59,
    porcDescuento: 0,
    codigoVendedor: 1,
    metodoPago: "Tarjeta",
    enviado: true,
    pick: true,
    pickStatus: true,
    comentariosPicking: "Urgente",
    estadoDocumento: 3,
    incidenciaDocumento: null,
    lineasPedidoCliente: [
      {
        numeroLinea: 0,
        codigoProducto: "8012",
        descripcion: "Café molido natural 500grs",
        fechaEnvio: "2025-11-25T00:00:00",
        cantidad: 2,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 4.50,
        precioConIVA: 4.95,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 0,
        importe: 9.00,
        totalLinea: 9.90,
        moneda: "EUR",
        codigoAlmacen: "01",
        pickStatus: 3,
        pickStatusEx: "S",
        codigoVendedor: 1,
        estadoLinea: 3,
        incidenciaLinea: null,
      },
      {
        numeroLinea: 1,
        codigoProducto: "9015",
        descripcion: "Galletas integrales 400grs",
        fechaEnvio: "2025-11-25T00:00:00",
        cantidad: 3,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 1.80,
        precioConIVA: 1.98,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 0,
        importe: 5.40,
        totalLinea: 5.94,
        moneda: "EUR",
        codigoAlmacen: "01",
        pickStatus: 3,
        pickStatusEx: "S",
        codigoVendedor: 1,
        estadoLinea: 3,
        incidenciaLinea: null,
      },
      {
        numeroLinea: 2,
        codigoProducto: "7010",
        descripcion: "Yogur natural 4 unidades",
        fechaEnvio: "2025-11-25T00:00:00",
        cantidad: 1,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 2.20,
        precioConIVA: 2.42,
        grupoIVA: "R1",
        porcIVA: 10,
        porcDescuento: 0,
        importe: 2.20,
        totalLinea: 2.42,
        moneda: "EUR",
        codigoAlmacen: "01",
        pickStatus: 3,
        pickStatusEx: "S",
        codigoVendedor: 1,
        estadoLinea: 3,
        incidenciaLinea: null,
      }
    ],
  },
  {
    entradaDocumento: 12,
    fechaDocumento: "2025-11-25T00:00:00",
    fechaCreacion: "2025-11-25T00:00:00",
    fechaActualizacion: "2025-11-25T00:00:00",
    codigoCliente: "C0000012",
    nombreCliente: "Carlos López",
    direccionEnvio: "Av. Diagonal 234, Barcelona",
    importeTotal: 15.75,
    importeIVA: 1.43,
    porcDescuento: 10,
    codigoVendedor: 2,
    metodoPago: "Bizum",
    enviado: false,
    pick: false,
    pickStatus: false,
    comentariosPicking: "",
    estadoDocumento: 1,
    incidenciaDocumento: null,
    lineasPedidoCliente: [
      {
        numeroLinea: 0,
        codigoProducto: "3015",
        descripcion: "Zumo de naranja 1L",
        fechaEnvio: "2025-11-25T00:00:00",
        cantidad: 2,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 2.10,
        precioConIVA: 2.31,
        grupoIVA: "R1",
        porcIVA: 10,
        porcDescuento: 10,
        importe: 3.78,
        totalLinea: 4.16,
        moneda: "EUR",
        codigoAlmacen: "02",
        pickStatus: 1,
        pickStatusEx: "N",
        codigoVendedor: 2,
        estadoLinea: 1,
        incidenciaLinea: null,
      },
      {
        numeroLinea: 1,
        codigoProducto: "5018",
        descripcion: "Aceitunas verdes sin hueso 200grs",
        fechaEnvio: "2025-11-25T00:00:00",
        cantidad: 1,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 1.95,
        precioConIVA: 2.15,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 10,
        importe: 1.76,
        totalLinea: 1.94,
        moneda: "EUR",
        codigoAlmacen: "02",
        pickStatus: 1,
        pickStatusEx: "N",
        codigoVendedor: 2,
        estadoLinea: 1,
        incidenciaLinea: null,
      }
    ],
  },
  {
    entradaDocumento: 13,
    fechaDocumento: "2025-11-26T00:00:00",
    fechaCreacion: "2025-11-26T00:00:00",
    fechaActualizacion: "2025-11-26T00:00:00",
    codigoCliente: "C0000013",
    nombreCliente: "Elena Martínez",
    direccionEnvio: "Calle Serrano 45, Madrid",
    importeTotal: 42.30,
    importeIVA: 3.85,
    porcDescuento: 0,
    codigoVendedor: 3,
    metodoPago: "Transferencia",
    enviado: true,
    pick: true,
    pickStatus: true,
    comentariosPicking: "Fragil - manejar con cuidado",
    estadoDocumento: 3,
    incidenciaDocumento: null,
    lineasPedidoCliente: [
      {
        numeroLinea: 0,
        codigoProducto: "6020",
        descripcion: "Vino blanco verdejo 750ml",
        fechaEnvio: "2025-11-26T00:00:00",
        cantidad: 2,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 8.50,
        precioConIVA: 9.35,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 0,
        importe: 17.00,
        totalLinea: 18.70,
        moneda: "EUR",
        codigoAlmacen: "03",
        pickStatus: 3,
        pickStatusEx: "S",
        codigoVendedor: 3,
        estadoLinea: 3,
        incidenciaLinea: null,
      },
      {
        numeroLinea: 1,
        codigoProducto: "7025",
        descripcion: "Queso brie 250grs",
        fechaEnvio: "2025-11-26T00:00:00",
        cantidad: 1,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 4.80,
        precioConIVA: 5.28,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 0,
        importe: 4.80,
        totalLinea: 5.28,
        moneda: "EUR",
        codigoAlmacen: "03",
        pickStatus: 3,
        pickStatusEx: "S",
        codigoVendedor: 3,
        estadoLinea: 3,
        incidenciaLinea: null,
      },
      {
        numeroLinea: 2,
        codigoProducto: "8020",
        descripcion: "Chocolate negro 70% 100grs",
        fechaEnvio: "2025-11-26T00:00:00",
        cantidad: 3,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 2.10,
        precioConIVA: 2.31,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 0,
        importe: 6.30,
        totalLinea: 6.93,
        moneda: "EUR",
        codigoAlmacen: "03",
        pickStatus: 3,
        pickStatusEx: "S",
        codigoVendedor: 3,
        estadoLinea: 3,
        incidenciaLinea: null,
      }
    ],
  },
  {
    entradaDocumento: 14,
    fechaDocumento: "2025-11-26T00:00:00",
    fechaCreacion: "2025-11-26T00:00:00",
    fechaActualizacion: "2025-11-26T00:00:00",
    codigoCliente: "C0000014",
    nombreCliente: "Javier Ruiz",
    direccionEnvio: "Plaza Mayor 12, Salamanca",
    importeTotal: 8.90,
    importeIVA: 0.81,
    porcDescuento: 0,
    codigoVendedor: 4,
    metodoPago: "Efectivo",
    enviado: false,
    pick: false,
    pickStatus: false,
    comentariosPicking: "",
    estadoDocumento: 1,
    incidenciaDocumento: null,
    lineasPedidoCliente: [
      {
        numeroLinea: 0,
        codigoProducto: "4010",
        descripcion: "Pan de centeno 500grs",
        fechaEnvio: "2025-11-26T00:00:00",
        cantidad: 1,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 2.80,
        precioConIVA: 3.08,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 0,
        importe: 2.80,
        totalLinea: 3.08,
        moneda: "EUR",
        codigoAlmacen: "01",
        pickStatus: 1,
        pickStatusEx: "N",
        codigoVendedor: 4,
        estadoLinea: 1,
        incidenciaLinea: null,
      },
      {
        numeroLinea: 1,
        codigoProducto: "9010",
        descripcion: "Cereales de avena 750grs",
        fechaEnvio: "2025-11-26T00:00:00",
        cantidad: 1,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 3.20,
        precioConIVA: 3.52,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 0,
        importe: 3.20,
        totalLinea: 3.52,
        moneda: "EUR",
        codigoAlmacen: "01",
        pickStatus: 1,
        pickStatusEx: "N",
        codigoVendedor: 4,
        estadoLinea: 1,
        incidenciaLinea: null,
      }
    ],
  },
  {
    entradaDocumento: 15,
    fechaDocumento: "2025-11-27T00:00:00",
    fechaCreacion: "2025-11-27T00:00:00",
    fechaActualizacion: "2025-11-27T00:00:00",
    codigoCliente: "C0000034",
    nombreCliente: "Daniel González",
    direccionEnvio: "Calle Invasores del Espacio 2, Zaragoza",
    importeTotal: 2.47,
    importeIVA: 0.25,
    porcDescuento: 0,
    codigoVendedor: 2,
    metodoPago: "Efectivo",
    enviado: false,
    pick: false,
    pickStatus: false,
    comentariosPicking: "",
    estadoDocumento: 3,
    incidenciaDocumento: null,
    lineasPedidoCliente: [
      {
        numeroLinea: 0,
        codigoProducto: "2091",
        descripcion: "Tomate frito Apis Brik 450grs",
        fechaEnvio: "2025-11-27T00:00:00",
        cantidad: 1,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 0.818,
        precioConIVA: 0.9,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 0,
        importe: 0.818,
        totalLinea: 0.82,
        moneda: "EUR",
        codigoAlmacen: "03",
        pickStatus: false,
        pickStatusEx: "N",
        codigoVendedor: 2,
        estadoLinea: 3,
        incidenciaLinea: null,
      },
      {
        numeroLinea: 1,
        codigoProducto: "2081",
        descripcion: "Patatas Fritas Lay's Jamón 180grs",
        fechaEnvio: "2025-11-27T00:00:00",
        cantidad: 1,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 1.436,
        precioConIVA: 1.57,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 0,
        importe: 1.436,
        totalLinea: 1.44,
        moneda: "EUR",
        codigoAlmacen: "03",
        pickStatus: 3,
        pickStatusEx: "N",
        codigoVendedor: 2,
        estadoLinea: 3,
        incidenciaLinea: null,
      },
    ],
  },
  {
    entradaDocumento: 16,
    fechaDocumento: "2025-11-27T00:00:00",
    fechaCreacion: "2025-11-27T00:00:00",
    fechaActualizacion: "2025-11-27T00:00:00",
    codigoCliente: "C0000004",
    nombreCliente: "Lucía Fernández",
    direccionEnvio: "Av. de la Libertad 12, Madrid, España",
    importeTotal: 2.47,
    importeIVA: 0.22,
    porcDescuento: 0,
    codigoVendedor: 3,
    metodoPago: "Tarjeta",
    enviado: false,
    pick: false,
    pickStatus: false,
    comentariosPicking: "",
    estadoDocumento: 1,
    incidenciaDocumento: null,
    lineasPedidoCliente: [
      {
        numeroLinea: 0,
        codigoProducto: "3021",
        descripcion: "Leche Asturiana semidesnatada 1l",
        fechaEnvio: "2025-11-27T00:00:00",
        cantidad: 2,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 1.125,
        precioConIVA: 1.24,
        grupoIVA: "R1",
        porcIVA: 10,
        porcDescuento: 0,
        importe: 1.125,
        totalLinea: 2.25,
        moneda: "EUR",
        codigoAlmacen: "01",
        pickStatus: 1,
        pickStatusEx: "N",
        codigoVendedor: 3,
        estadoLinea: 1,
        incidenciaLinea: null,
      },
      {
        numeroLinea: 1,
        codigoProducto: "4023",
        descripcion: "Pan de molde Bimbo 450grs",
        fechaEnvio: "2025-11-27T00:00:00",
        cantidad: 1,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 0.55,
        precioConIVA: 0.60,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 0,
        importe: 0.55,
        totalLinea: 0.60,
        moneda: "EUR",
        codigoAlmacen: "01",
        pickStatus: 2,
        pickStatusEx: "N",
        codigoVendedor: 3,
        estadoLinea: 1,
        incidenciaLinea: null,
      },
    ],
  },
  {
    codigoCliente: "C0000002",
    direccionEnvio: "C/ Rufino Blanco 24, Guadalajara",
    entradaDocumento: 17,
    enviado: true,
    estadoDocumento: 1,
    fechaActualizacion: "2025-11-27T00:00:00",
    fechaCreacion: "2025-11-27T00:00:00",
    fechaDocumento: "2025-11-27T00:00:00",
    importeIVA: 0.34,
    importeTotal: 3.71,
    incidenciaDocumento: "",
    metodoPago: "Bizum",
    nombreCliente: "Pedro Martínez",
    pick: false,
    pickStatus: false,
    porcDescuento: 0,
    lineasPedidoCliente: [
      {
        numeroLinea: 0,
        codigoProducto: "6031",
        descripcion: "Bote de mayonesa 250grs",
        fechaEnvio: "2025-11-27T00:00:00",
        cantidad: 1,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 1.909,
        precioConIVA: 2.1,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 0,
        importe: 1.909,
        totalLinea: 1.91,
        moneda: "EUR",
        codigoAlmacen: "03",
        pickStatus: false,
        pickStatusEx: "N",
        codigoVendedor: 0,
        estadoLinea: 1,
        incidenciaLinea: null,
      },
      {
        numeroLinea: 1,
        codigoProducto: "9381",
        descripcion: "Picos de pan 160grs",
        fechaEnvio: "2025-11-27T00:00:00",
        cantidad: 1,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 1.455,
        precioConIVA: 1.6,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 0,
        importe: 1.455,
        totalLinea: 1.46,
        moneda: "EUR",
        codigoAlmacen: "03",
        pickStatus: false,
        pickStatusEx: "N",
        codigoVendedor: 0,
        estadoLinea: 1,
        incidenciaLinea: null,
      },
    ],
  },
  {
    entradaDocumento: 18,
    fechaDocumento: "2025-11-28T00:00:00",
    fechaCreacion: "2025-11-28T00:00:00",
    fechaActualizacion: "2025-11-28T00:00:00",
    codigoCliente: "C0000005",
    nombreCliente: "María González",
    direccionEnvio: "Calle Mayor 45, Barcelona, España",
    importeTotal: 45.80,
    importeIVA: 4.16,
    porcDescuento: 5,
    codigoVendedor: 4,
    metodoPago: "Tarjeta",
    enviado: false,
    pick: false,
    pickStatus: false,
    comentariosPicking: "Productos frágiles",
    estadoDocumento: 1,
    incidenciaDocumento: null,
    lineasPedidoCliente: [
      {
        numeroLinea: 0,
        codigoProducto: "5012",
        descripcion: "Aceite de oliva virgen extra 1l",
        fechaEnvio: "2025-11-28T00:00:00",
        cantidad: 3,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 8.50,
        precioConIVA: 9.35,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 5,
        importe: 24.23,
        totalLinea: 26.65,
        moneda: "EUR",
        codigoAlmacen: "02",
        pickStatus: 1,
        pickStatusEx: "N",
        codigoVendedor: 4,
        estadoLinea: 1,
        incidenciaLinea: null,
      },
      {
        numeroLinea: 1,
        codigoProducto: "6015",
        descripcion: "Vino Tinto Reserva 750ml",
        fechaEnvio: "2025-11-28T00:00:00",
        cantidad: 2,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 12.00,
        precioConIVA: 13.20,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 5,
        importe: 22.80,
        totalLinea: 25.08,
        moneda: "EUR",
        codigoAlmacen: "02",
        pickStatus: 1,
        pickStatusEx: "N",
        codigoVendedor: 4,
        estadoLinea: 1,
        incidenciaLinea: null,
      },
      {
        numeroLinea: 2,
        codigoProducto: "7018",
        descripcion: "Queso manchego 500grs",
        fechaEnvio: "2025-11-28T00:00:00",
        cantidad: 1,
        cantidadPaquetes: 1,
        elementosPorUnidad: 1,
        precioUnidad: 6.80,
        precioConIVA: 7.48,
        grupoIVA: "R2",
        porcIVA: 10,
        porcDescuento: 5,
        importe: 6.46,
        totalLinea: 7.11,
        moneda: "EUR",
        codigoAlmacen: "02",
        pickStatus: 1,
        pickStatusEx: "N",
        codigoVendedor: 4,
        estadoLinea: 1,
        incidenciaLinea: null,
      }
    ],
  }
];